import { Module } from "@nestjs/common";
import { IdentityGuard } from "../common/guards/identity.guard.js";
import { SuperAdminGuard } from "../common/guards/super-admin.guard.js";
import { PrismaService } from "../database/prisma.service.js";
import {
  DepositRepository,
  ExpenseRepository,
  FinanceCategoryRepository,
  FinanceDashboardRepository,
  FinanceKanbanRepository,
  IncomeRepository,
  PaymentPaypalRepository,
  PaymentValorRepository,
  SuperAdminExpenseRepository,
  SuperAdminFinanceRepository,
  TaxSalesRepository,
} from "./finance.repositories.js";
import {
  DepositService,
  ExpenseService,
  FinanceCategoryService,
  FinanceDashboardService,
  FinanceKanbanService,
  IncomeService,
  PaymentPaypalService,
  PaymentValorService,
  SuperAdminFinanceService,
  TaxSalesService,
} from "./finance.services.js";
import {
  DepositController,
  ExpenseController,
  FinanceCategoryController,
  IncomeController,
  LegacyFinanceCategoryController,
  LegacyFinanceDashboardController,
  LegacyFinanceKanbanController,
  LegacySuperAdminFinanceController,
  PaymentPaypalController,
  PaymentValorController,
  SuperAdminFinanceController,
  TaxSalesController,
} from "./finance.controllers.js";

@Module({
  controllers: [
    IncomeController,
    ExpenseController,
    DepositController,
    PaymentPaypalController,
    PaymentValorController,
    FinanceCategoryController,
    TaxSalesController,
    SuperAdminFinanceController,
    LegacyFinanceCategoryController,
    LegacyFinanceDashboardController,
    LegacyFinanceKanbanController,
    LegacySuperAdminFinanceController,
  ],
  providers: [
    PrismaService,
    IncomeRepository,
    ExpenseRepository,
    DepositRepository,
    PaymentPaypalRepository,
    PaymentValorRepository,
    FinanceCategoryRepository,
    TaxSalesRepository,
    FinanceDashboardRepository,
    FinanceKanbanRepository,
    SuperAdminFinanceRepository,
    SuperAdminExpenseRepository,
    IncomeService,
    ExpenseService,
    DepositService,
    PaymentPaypalService,
    PaymentValorService,
    FinanceCategoryService,
    TaxSalesService,
    FinanceDashboardService,
    FinanceKanbanService,
    SuperAdminFinanceService,
    IdentityGuard,
    SuperAdminGuard,
  ],
})
export class FinanceModule {}
