export const INITIAL_MOCK_DATA: Record<string, any[]> = {
  'res.partner': [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@acme.corp',
      phone: '+1 555-0101',
      city: 'San Francisco',
      is_company: false,
    },
    {
      id: 2,
      name: 'Acme Corp',
      email: 'info@acme.corp',
      phone: '+1 555-0202',
      city: 'San Francisco',
      is_company: true,
    },
    {
      id: 3,
      name: 'Jane Smith',
      email: 'jane@globex.it',
      phone: '+1 555-0303',
      city: 'Milan',
      is_company: false,
    },
  ],
  'crm.lead': [
    {
      id: 1,
      name: 'Enterprise Cloud Migration',
      planned_revenue: 150000,
      probability: 40,
      stage_id: [1, 'New'],
    },
    {
      id: 2,
      name: 'Mobile App Development',
      planned_revenue: 45000,
      probability: 80,
      stage_id: [3, 'Proposition'],
    },
  ],
  'account.move': [
    {
      id: 1,
      name: 'INV/2024/001',
      amount_total: 1200,
      state: 'posted',
      payment_state: 'paid',
      invoice_date: '2024-03-01',
    },
    {
      id: 2,
      name: 'INV/2024/002',
      amount_total: 3500,
      state: 'posted',
      payment_state: 'not_paid',
      invoice_date: '2024-03-15',
    },
  ],
  'product.template': [
    {
      id: 1,
      name: 'iPhone 15 Pro Max',
      default_code: 'IP15-PM-256',
      list_price: 1199.0,
      type: 'consu',
      qty_available: 42,
      barcode: '194253702111',
      description: 'The ultimate iPhone with titanium design and A17 Pro chip.',
      photos: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569'],
    },
    {
      id: 2,
      name: 'MacBook Pro 16" M3 Max',
      default_code: 'MBP16-M3M-64',
      list_price: 3499.0,
      type: 'consu',
      qty_available: 15,
      barcode: '194253702222',
      description: 'The most powerful MacBook ever built for professionals.',
      photos: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8'],
    },
    {
      id: 3,
      name: 'AirPods Max - Sky Blue',
      default_code: 'APM-BLUE',
      list_price: 549.0,
      type: 'consu',
      qty_available: 120,
      barcode: '194253702333',
      description:
        'High-fidelity audio meets industry-leading active noise cancellation.',
      photos: ['https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3'],
    },
    {
      id: 4,
      name: 'Sony A7 IV Mirrorless',
      default_code: 'SONY-A74',
      list_price: 2499.0,
      type: 'consu',
      qty_available: 8,
      barcode: '194253702444',
      description:
        'Full-frame mirrorless camera for enthusiasts and pros alike.',
      photos: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32'],
    },
  ],
  'product.category': [
    { id: 1, name: 'Electronics', is_active: true },
    { id: 2, name: 'Computers', is_active: true },
    { id: 3, name: 'Audio', is_active: true },
    { id: 4, name: 'Photography', is_active: true },
  ],
  'sale.order': [
    {
      id: 1,
      name: 'S0001',
      state: 'sale',
      amount_total: 1199.0,
      date_order: '2024-04-20 10:00:00',
      partner_id: [1, 'Azure Interior'],
      order_line: [
        { id: 1, name: 'iPhone 15 Pro Max', qty_ordered: 1, price: 1199.0 },
      ],
    },
  ],
  'blog.post': [],
  'project.project': [
    {
      id: 1,
      name: 'Website Redesign',
      user_id: [1, 'Admin'],
      date_start: '2024-01-01',
      label_tasks: 'Tasks',
    },
    {
      id: 2,
      name: 'Mobile App Launch',
      user_id: [1, 'Admin'],
      date_start: '2024-02-15',
      label_tasks: 'Milestones',
    },
  ],
  'project.task': [
    {
      id: 1,
      name: 'Design Homepage',
      project_id: [1, 'Website Redesign'],
      stage_id: [1, 'New'],
      priority: '0',
    },
    {
      id: 2,
      name: 'Setup Database',
      project_id: [2, 'Mobile App Launch'],
      stage_id: [2, 'In Progress'],
      priority: '1',
    },
  ],
  'account.analytic.line': [],
};
