FROM node:24-alpine

ARG SERVICE_NAME
ARG SERVICE_PORT

ENV SERVICE_NAME=${SERVICE_NAME}
ENV PORT=${SERVICE_PORT}
ENV NODE_ENV=development

WORKDIR /workspace/services/${SERVICE_NAME}

RUN corepack enable

EXPOSE ${SERVICE_PORT}

CMD ["npm", "run", "dev"]
