apiVersion: v1
kind: Service
metadata:
  name: organization-service
  labels:
    app.kubernetes.io/name: organization-service
spec:
  selector:
    app.kubernetes.io/name: organization-service
  ports:
    - name: http
      port: 7010
      targetPort: 7010
