apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mymanager-dev

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/mymanager/organization-service
    newTag: dev

patches:
  - path: keycloak-dev-patch.yaml
    target:
      kind: Deployment
      name: keycloak
