
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AutomationScalarFieldEnum = {
  id: 'id',
  automationName: 'automationName',
  contactInfo: 'contactInfo',
  activationUpon: 'activationUpon',
  activateTime: 'activateTime',
  userEmail: 'userEmail',
  userPhone: 'userPhone',
  userName: 'userName',
  userId: 'userId',
  organizationId: 'organizationId',
  isActive: 'isActive',
  isDelete: 'isDelete',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  workspaceId: 'workspaceId',
  title: 'title',
  description: 'description',
  status: 'status',
  verticalFlow: 'verticalFlow',
  creatorType: 'creatorType',
  isForSystemNotification: 'isForSystemNotification',
  isForUserNotification: 'isForUserNotification',
  isForClientNotification: 'isForClientNotification',
  isCopyFromSystemNotification: 'isCopyFromSystemNotification',
  parentWorkflowId: 'parentWorkflowId',
  isDeleted: 'isDeleted',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowNodeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  workflowId: 'workflowId',
  key: 'key',
  data: 'data',
  type: 'type',
  source: 'source',
  height: 'height',
  width: 'width',
  position: 'position',
  positionAbsolute: 'positionAbsolute',
  sourcePosition: 'sourcePosition',
  targetPosition: 'targetPosition',
  isDeleted: 'isDeleted',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowWorkspaceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  isDeleted: 'isDeleted',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowStartActionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  workflowId: 'workflowId',
  actionType: 'actionType',
  duration: 'duration',
  parentId: 'parentId',
  setCustomTime: 'setCustomTime',
  useSubscriberTimeZone: 'useSubscriberTimeZone',
  customTime: 'customTime',
  subject: 'subject',
  content: 'content',
  template: 'template',
  attachments: 'attachments',
  condition: 'condition',
  confirmProgress: 'confirmProgress',
  notificationTo: 'notificationTo',
  taskContent: 'taskContent',
  isStart: 'isStart',
  isLast: 'isLast',
  isCondition: 'isCondition',
  isException: 'isException',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowActivityLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  workflowId: 'workflowId',
  contactId: 'contactId',
  nodeId: 'nodeId',
  action: 'action',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.WorkflowExecutionHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  workflowId: 'workflowId',
  contactId: 'contactId',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt'
};

exports.Prisma.OmniChatbotScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  provider: 'provider',
  isActive: 'isActive',
  aiEnabled: 'aiEnabled',
  aiPrompt: 'aiPrompt',
  welcomeMessage: 'welcomeMessage',
  fallbackMessage: 'fallbackMessage',
  flowData: 'flowData',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OmniContactFlowStateScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  contactMobile: 'contactMobile',
  chatbotId: 'chatbotId',
  currentNodeId: 'currentNodeId',
  stateData: 'stateData',
  lastInteraction: 'lastInteraction',
  isCompleted: 'isCompleted'
};

exports.Prisma.OmniKeywordTriggerScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  keyword: 'keyword',
  matchType: 'matchType',
  workflowId: 'workflowId',
  replyMessage: 'replyMessage',
  isActive: 'isActive',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OmniBroadcastScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  name: 'name',
  provider: 'provider',
  instanceId: 'instanceId',
  content: 'content',
  type: 'type',
  mediaUrl: 'mediaUrl',
  scheduledAt: 'scheduledAt',
  status: 'status',
  totalCount: 'totalCount',
  sentCount: 'sentCount',
  deliveredCount: 'deliveredCount',
  readCount: 'readCount',
  failedCount: 'failedCount',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OmniBroadcastRecipientScalarFieldEnum = {
  id: 'id',
  broadcastId: 'broadcastId',
  contactId: 'contactId',
  mobile: 'mobile',
  variables: 'variables',
  status: 'status',
  errorMessage: 'errorMessage',
  processedAt: 'processedAt'
};

exports.Prisma.OmniWebhookScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  secret: 'secret',
  workflowId: 'workflowId',
  chatbotId: 'chatbotId',
  isActive: 'isActive',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OmniWebhookLogScalarFieldEnum = {
  id: 'id',
  webhookId: 'webhookId',
  payload: 'payload',
  headers: 'headers',
  status: 'status',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Automation: 'Automation',
  Workflow: 'Workflow',
  WorkflowNode: 'WorkflowNode',
  WorkflowWorkspace: 'WorkflowWorkspace',
  WorkflowStartAction: 'WorkflowStartAction',
  WorkflowActivityLog: 'WorkflowActivityLog',
  WorkflowExecutionHistory: 'WorkflowExecutionHistory',
  OmniChatbot: 'OmniChatbot',
  OmniContactFlowState: 'OmniContactFlowState',
  OmniKeywordTrigger: 'OmniKeywordTrigger',
  OmniBroadcast: 'OmniBroadcast',
  OmniBroadcastRecipient: 'OmniBroadcastRecipient',
  OmniWebhook: 'OmniWebhook',
  OmniWebhookLog: 'OmniWebhookLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
