
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ContactMapScalarFieldEnum = {
  uuid: 'uuid',
  odooId: 'odooId',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.PetScalarFieldEnum = {
  id: 'id',
  contactId: 'contactId',
  name: 'name',
  breed: 'breed',
  age: 'age',
  birthDate: 'birthDate',
  photo: 'photo',
  createdAt: 'createdAt'
};

exports.Prisma.ContactFileScalarFieldEnum = {
  id: 'id',
  contactId: 'contactId',
  name: 'name',
  size: 'size',
  url: 'url',
  type: 'type',
  createdAt: 'createdAt'
};

exports.Prisma.ContactTaskScalarFieldEnum = {
  id: 'id',
  contactId: 'contactId',
  title: 'title',
  dueDate: 'dueDate',
  priority: 'priority',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.ContactActivityScalarFieldEnum = {
  id: 'id',
  contactId: 'contactId',
  type: 'type',
  title: 'title',
  content: 'content',
  author: 'author',
  color: 'color',
  icon: 'icon',
  createdAt: 'createdAt'
};

exports.Prisma.ContactShiftScalarFieldEnum = {
  id: 'id',
  contactId: 'contactId',
  clockIn: 'clockIn',
  clockOut: 'clockOut',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.MarketingSuppressionEntryScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  channel: 'channel',
  value: 'value',
  reason: 'reason',
  source: 'source',
  createdAt: 'createdAt'
};

exports.Prisma.MarketingContactConsentScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  contactId: 'contactId',
  emailOptIn: 'emailOptIn',
  smsOptIn: 'smsOptIn',
  unsubscribed: 'unsubscribed',
  updatedByUser: 'updatedByUser',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.MarketingCampaignTemplateUsageScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  campaignId: 'campaignId',
  templateId: 'templateId',
  templateVersionId: 'templateVersionId',
  templateNameSnapshot: 'templateNameSnapshot',
  subjectSnapshot: 'subjectSnapshot',
  previewTextSnapshot: 'previewTextSnapshot',
  contentSnapshot: 'contentSnapshot',
  appliedByUserId: 'appliedByUserId',
  appliedAt: 'appliedAt',
  createdAt: 'createdAt'
};

exports.Prisma.MarketingDeliveryEventScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  campaignId: 'campaignId',
  recipientId: 'recipientId',
  recipientEmail: 'recipientEmail',
  recipientPhone: 'recipientPhone',
  provider: 'provider',
  providerEventId: 'providerEventId',
  providerMessageId: 'providerMessageId',
  eventType: 'eventType',
  url: 'url',
  reason: 'reason',
  rawPayload: 'rawPayload',
  occurredAt: 'occurredAt',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  ContactMap: 'ContactMap',
  Pet: 'Pet',
  ContactFile: 'ContactFile',
  ContactTask: 'ContactTask',
  ContactActivity: 'ContactActivity',
  ContactShift: 'ContactShift',
  MarketingSuppressionEntry: 'MarketingSuppressionEntry',
  MarketingContactConsent: 'MarketingContactConsent',
  MarketingCampaignTemplateUsage: 'MarketingCampaignTemplateUsage',
  MarketingDeliveryEvent: 'MarketingDeliveryEvent'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
