apiVersion: v1
kind: Service
metadata:
  name: organization-db
  labels:
    app.kubernetes.io/name: organization-db
spec:
  selector:
    app.kubernetes.io/name: organization-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: organization-db
  labels:
    app.kubernetes.io/name: organization-db
spec:
  serviceName: organization-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: organization-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: organization-db
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: organization-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
