apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mymanager-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.mymanager.example.com
      secretName: mymanager-api-tls
  rules:
    - host: api.mymanager.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 8081
